<a href="https://colab.research.google.com/github/jmlly/curso-machine-learning/blob/main/aula06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #np = apelido, falcilita o uso da ferramenta.

In [ ]:
minhaLista = [0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [ ]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array3 = np.arange(0,15,0.5)
array3

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [ ]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10., 10., 10., 11., 12., 12., 12.,
       13., 14., 14., 14.])

In [ ]:
array3 = np.arange(0,10,0.5, dtype=int) #"forçando o tipo dos elementos"
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array4 = np.arange(12.) #array preparado para trabalhar com float no futuro
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
type(array4)

numpy.ndarray

In [ ]:
array4.dtype

dtype('float64')

In [ ]:
vetor1 = np.array([0,1,2,3,4])  #criar uma array digitando os valores
print(vetor1)

[0 1 2 3 4]


In [ ]:
vetor1[3]#selecionando um elemento especifico

3

In [ ]:
vetor1[0:2] #selecionando um intervalo especifico

array([0, 1])

In [ ]:
print(vetor1[0:2])

[0 1]


In [ ]:
s = np.array(['Python','Profissional','Java','Agua'])
s

array(['Python', 'Profissional', 'Java', 'Agua'], dtype='<U12')

In [ ]:
s = np.array(['Python',1432432, 'Profissional','Java','Agua'])
s

array(['Python', '1432432', 'Profissional', 'Java', 'Agua'], dtype='<U21')

In [ ]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
vetor1[0] = 'novo elemento'
vetor1

ValueError: ignored

In [ ]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

In [ ]:
s[0] = 'novo elemento'
s

array(['novo elemento', '1432432', 'Profissional', 'Java', 'Agua'],
      dtype='<U21')