<a href="https://colab.research.google.com/github/jmlly/curso-machine-learning/blob/main/Aulas/Aula09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Definindo os dados de treino**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#tosse?
#espirro?
#falta de ar?
#febre?
#usando 0 para não e 1 para sim

gripado1 = [1,1,1,1] #informando ao algoritmo grupo de pessoas que estão com gripe
gripado2 = [0,1,0,1]
gripado3 = [1,1,0,0]
gripado4 = [1,1,0,1]

alergico1 = [1,1,0,0] #apresentando ao algoritmo grupo de pessoas que não estão doentes mas possuem sintomas
alergico2 = [0,1,0,0]
alergico3 = [1,0,1,0]
alergico4 = [0,1,1,0]

In [7]:
dados = [gripado1, gripado2, gripado3, gripado4, alergico1, alergico2, alergico3, alergico4]
#categoria 1 = gripado; categoria 0 = alergico
categorias = [1,1,1,1,0,0,0,0]

In [8]:
from sklearn.svm import LinearSVC

**Rodando nosso treino**

In [9]:
modelo = LinearSVC()
modelo.fit(dados, categorias)

LinearSVC()

**Defininção dados de teste**

Os dados de teste são os dados que a gente **já conhece** o resultado e vai medir se o algoritmo está acertando as privisões

In [23]:
paciente1 = [0,1,0,1]
paciente2 = [0,0,0,0]
paciente3 = [1,1,1,1]
paciente4 = [0,1,0,1]

dados_teste = [paciente1,paciente2,paciente3,paciente4]

**Testando**

In [24]:
modelo.predict(dados_teste)

array([1, 0, 1, 1])

O algoritmo preveu que o primeiro paciente está doente, o segundo não, o terceiro e quarto estão.

Dado um novo paciente, vamos avaliar a possibilidade de ele estar gripado:

In [25]:
novo_paciente = [0,1,0,0]
modelo.predict([novo_paciente])

array([0])

In [27]:
if (modelo.predict([novo_paciente]) == 0):
  print('Paciente potencialmente alérgico')
else:
  print('Paciente potencialmente gripado')

Paciente potencialmente alérgico


Vamos salvar a aplicação do nosso modelo sobre os dados de teste na variável predições

In [28]:
predicoes = modelo.predict(dados_teste)

In [29]:
#Vamos supor que temos casos com exames que confirmaram o seguinte sobre os pacientes terem gripe ou nao
#vamos comparar nosso modelo com a realidade
exames = [1,0,1,0]

In [30]:
predicoes == exames

array([ True,  True,  True, False])

Descobrindo quanto o algoritmo acertou no teste:

In [31]:
total_acertos = (predicoes == exames).sum()
total_acertos

3

Previsões totais:

In [32]:
total_predicoes = len(dados_teste)
total_predicoes

4

Nossa taxa de sucesso:

In [33]:
taxa_sucesso = total_acertos / total_predicoes * 100
taxa_sucesso

75.0

In [34]:
print('A taxa de sucesso do seu modelo preditivo foi de ', taxa_sucesso, '%. ' )

A taxa de sucesso do seu modelo preditivo foi de  75.0 %. 


Para situações mais complexas, usaremos o accuracy score

In [ ]:
from sklearn.metrics import accuracy_score
taxa_sucesso = accuracy_score(total_acertos / total_predicoes) #erro por falta do y_pred, assunto da proxima aula